"""add video table

Revision ID: 1826382d9151
Revises: db3f47f3c998
Create Date: 2026-01-29 10:21:07.459502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1826382d9151'
down_revision = 'db3f47f3c998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False, comment='视频id'),
    sa.Column('video_url', sa.String(length=255), nullable=False, comment='视频路径'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='所在区域'),
    sa.Column('format', sa.String(length=20), nullable=True, comment='视频格式'),
    sa.Column('upload_time', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('upload_by', sa.Integer(), nullable=True, comment='上传的管理员ID'),
    sa.Column('camera_id', sa.Integer(), nullable=True, comment='当前关联的摄像头ID'),
    sa.Column('config_status', sa.String(length=50), nullable=True, comment='配置状态'),
    sa.Column('assigned_time', sa.DateTime(), nullable=True, comment='分配时间'),
    sa.ForeignKeyConstraint(['upload_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###
