"""alter video table

Revision ID: 1c296c485790
Revises: 32015cb51878
Create Date: 2026-01-30 16:27:45.706111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c296c485790'
down_revision = '32015cb51878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('assigned_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_time', mysql.DATETIME(), nullable=True, comment='分配时间'))

    # ### end Alembic commands ###
