"""add violation_event table

Revision ID: 23e479e36599
Revises: 1c296c485790
Create Date: 2026-02-04 10:44:25.151882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e479e36599'
down_revision = '1c296c485790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False, comment='事件id'),
    sa.Column('camera_id', sa.Integer(), nullable=False, comment='摄像头id'),
    sa.Column('bicycle_id', sa.Integer(), nullable=False, comment='单车目标id'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='违停开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='违停停止时间'),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.camera_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_event')
    # ### end Alembic commands ###
