"""add camera table

Revision ID: 2e2391ee07ea
Revises: 6c9d73f285f5
Create Date: 2026-01-30 14:45:46.916251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2391ee07ea'
down_revision = '6c9d73f285f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_name', sa.String(length=100), nullable=True, comment='摄像头名称'))
        batch_op.add_column(sa.Column('video_id', sa.String(length=50), nullable=True, comment='视频id'))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
        batch_op.alter_column('camera_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               comment='摄像头id',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['user_id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user_camera_permission', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=mysql.INTEGER(),
               comment='权限id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=False)
        batch_op.alter_column('camera_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               comment='摄像头id',
               existing_nullable=False)
        batch_op.alter_column('granted_at',
               existing_type=mysql.DATETIME(),
               comment='授权时间',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'camera', ['camera_id'], ['camera_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_camera_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('granted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='授权时间',
               existing_nullable=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='摄像头id',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='权限id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('camera_id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='摄像头id',
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('video_id')
        batch_op.drop_column('camera_name')

    # ### end Alembic commands ###
