"""alter camera table

Revision ID: 32015cb51878
Revises: f3a1c58bf84b
Create Date: 2026-01-30 15:21:15.519011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32015cb51878'
down_revision = 'f3a1c58bf84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_comment='视频id',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_comment='视频id',
               existing_nullable=True)

    # ### end Alembic commands ###
