"""add sys_config table

Revision ID: 51bfc492603f
Revises: f8d11a8b0b91
Create Date: 2026-02-13 11:30:57.644138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bfc492603f'
down_revision = 'f8d11a8b0b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False, comment='参数id'),
    sa.Column('config_key', sa.String(length=50), nullable=False, comment='参数名'),
    sa.Column('config_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='参数值'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='参数单位'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='参数说明'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='参数更新时间'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_config')
    # ### end Alembic commands ###
