"""alter camera table

Revision ID: 67d645c5cbc2
Revises: 2e2391ee07ea
Create Date: 2026-01-30 15:06:01.840239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d645c5cbc2'
down_revision = '2e2391ee07ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('camera_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_comment='摄像头id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_camera_permission', schema=None) as batch_op:
        batch_op.alter_column('camera_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_comment='摄像头id',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_camera_permission', schema=None) as batch_op:
        batch_op.alter_column('camera_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_comment='摄像头id',
               existing_nullable=False)

    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.alter_column('camera_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_comment='摄像头id',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
