"""alter video table

Revision ID: 6c9d73f285f5
Revises: 1826382d9151
Create Date: 2026-01-29 11:26:35.774808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9d73f285f5'
down_revision = '1826382d9151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_name', sa.String(length=100), nullable=True, comment='视频源名称'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('video_name')

    # ### end Alembic commands ###
