"""添加验证码数据库表

Revision ID: db3f47f3c998
Revises: 9d779a97b0d9
Create Date: 2025-12-22 22:02:23.142671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3f47f3c998'
down_revision = '9d779a97b0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_code_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_code_email'))

    op.drop_table('verification_code')
    # ### end Alembic commands ###
