"""Recreate camera table

Revision ID: f3a1c58bf84b
Revises: 67d645c5cbc2
Create Date: 2026-01-30 15:19:04.269579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a1c58bf84b'
down_revision = '67d645c5cbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('camera_id', sa.Integer(), autoincrement=True, nullable=False, comment='摄像头id'),
    sa.Column('camera_name', sa.String(length=100), nullable=True, comment='摄像头名称'),
    sa.Column('video_id', sa.String(length=50), nullable=True, comment='视频id'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('user_camera_permission',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False, comment='权限id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('camera_id', sa.Integer(), nullable=False, comment='摄像头id'),
    sa.Column('granted_at', sa.DateTime(), nullable=True, comment='授权时间'),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.camera_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_camera_permission')
    op.drop_table('camera')
    # ### end Alembic commands ###
