"""add created_at to AlertRecord

Revision ID: f8d11a8b0b91
Revises: 23e479e36599
Create Date: 2026-02-08 15:42:29.158037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d11a8b0b91'
down_revision = '23e479e36599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='告警创建时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_record', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
